name: Publish package to GitHub
on:
  pull_request:
    types: 
      - closed
    branches:
      - main
    paths:
      - 'packages/**'
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      
      - name: "Setup Node environment"
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@jwhazel'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      
      - name: "Setup git"
        env:
          GH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor}}@users.noreply.github.com"

      - name: "Version and publish"
        run: |
          npm ci
          npx lerna version --conventional-commits --yes
          npx lerna publish from-git --yes